package com.agicomputers.LoanAPI.models.enums;
public enum  UserOccupation{
TEACHER("TEACHER"),
LAWYER("LAWYER"),
MEDICAL_DOCTOR("MEDICAL_DOCTOR"),
NURSE("NURSE"),
CIVIL_ENGINEER("CIVIL_ENGINEER"),
COMPUTER_ENGINEER("COMPUTER_ENGINEER"),
ELECTRICAL_ELECTRONICS_ENGINEER("ELECTRICAL_ELECTRONICS_ENGINEER"),
CHEMICAL_ENGINEER("CHEMICAL_ENGINEER"),
MECHANICAL_ENGINEER("MECHANICAL_ENGINEER"),
FASHION_DESIGNER("FASHION_DESIGNER"),
IT_CONSULTANT("IT_CONSULTANT"),
ARTISAN("ARTISAN"),
COOK("COOK"),
CLEANER("CLEANER"),
SECRETARY("SECRETARY"),
BAKER("BAKER"),
SALES_PERSON("SALES_PERSON"),
POLICE_OFFICER("POLICE_OFFICER"),
ARMED_FORCES("ARMED_FORCES"),
NAVY("NAVY");

    private String occupation;

    UserOccupation(String occupation){this.occupation = occupation;}
}